-- 코드를 입력하세요
SELECT PRODUCT_CODE, SALE*PRICE as SALES
FROM PRODUCT
JOIN (select PRODUCT_ID,sum(SALES_AMOUNT) as SALE
     from OFFLINE_SALE
     group by PRODUCT_ID) as OS
ON PRODUCT.PRODUCT_ID = OS.PRODUCT_ID
order by SALES desc,PRODUCT_CODE
     
